### ISSUE TITLE
Vps deploy guide

### ISSUE THREAD

**Issue by ramanveerji** [Guru322/GURU-BOT#116]
Please post vps deploy guide also

**Comment by Guru322** [comment]
[vps deploy guide](https://github.com/Guru322/GURU-BOT/blob/main/Termux-Guide.md)

As you are on a Vps , you don't really need vars

 you can checkout vars [Here](https://github.com/Guru322/GURU-BOT/blob/main/sample.env)

**Comment by ramanveerji** [comment]
> [vps deploy guide](https://github.com/Guru322/GURU-BOT/blob/main/Termux-Guide.md)
> 
> As you are on a Vps , you don't really need vars
> 
>  you can checkout vars [Here](https://github.com/Guru322/GURU-BOT/blob/main/sample.env)

Will reply surely after trying.
