### ISSUE TITLE
❎ An unexpected error occurred: SIGKILL

### ISSUE THREAD

**Issue by Ballarina** [Guru322/GURU-BOT#12]
The running process is constantly being terminated for no apparent reason.  Why is that?

❎ An unexpected error occurred: SIGKILL

On koyeb and also on doprax

**Comment by Guru322** [comment]
Doprax and koyeb offer limited memory in their free tier ,so when the memory runs out  SIGKILL occurs ,

you can upgrade to a paid plan of these platforms to get more memory and RAM 

or you can lower bot load like add bot in less groups 

or wait till i get an alternative solution


THANKS FOR USING GURU-BOT

**Comment by Aries866** [comment]
> Doprax and koyeb offer limited memory in their free tier ,so when the memory runs out SIGKILL occurs ,
> 
> you can upgrade to a paid plan of these platforms to get more memory and RAM
> 
> or you can lower bot load like add bot in less groups
> 
> or wait till i get an alternative solution
> 
> THANKS FOR USING GURU-BOT

but same problem in railway or  in pc o how the solutions is this

**Comment by Guru322** [comment]
I think you are on Railway free plan
I have Deployed Bot on railway dev plan before 
And it not giving any problem

About in pc , can you give more info ?

**Comment by Guru322** [comment]
![IMG_20230503_095857](https://user-images.githubusercontent.com/106463398/235833157-76f19a0d-a59e-4cd4-80a6-f9da91357524.jpg)

You can check out new deploy method `https://youtu.be/hBxSyqyeoFU` Here

**Comment by Jishnux3** [comment]
![Screenshot_2023-07-14-04-42-44-816_com termux](https://github.com/Guru322/GURU-BOT/assets/116358924/9ee70c80-3e64-4cab-84b9-418be3234e72)
![Screenshot_2023-07-14-04-42-49-787_com termux](https://github.com/Guru322/GURU-BOT/assets/116358924/3ec3c8b4-3e87-4c9d-9deb-aa127f2ddcd5)
