### ISSUE TITLE
KhoolKheed

### ISSUE THREAD

**Issue by T-code-bit** [Guru322/GURU-BOT#141]

**Comment by Guru322** [comment]
Atleast say something what's the issue 👉😔👈

**Comment by T-code-bit** [comment]
Okay the QR is taking long than expected to connect

**Comment by Guru322** [comment]
loading for longer time ?

use Another Browser

**Comment by T-code-bit** [comment]
Thanks for the tip!

**Comment by T-code-bit** [comment]
Awesome, thanks for the update!
