### ISSUE TITLE
No Response after successful deployment

### ISSUE THREAD

**Issue by aitzaz70** [Guru322/GURU-BOT#148]

**Comment by Guru322** [comment]
Maybe you have too many unread chats or old session id

**Comment by aitzaz70** [comment]
> Maybe you have too many unread chats or old session id

i deployed it more than twice but still no response after successful deployment

![image](https://github.com/Guru322/GURU-BOT/assets/63487695/a59f42bd-88e5-4f86-9216-a48a52c01bbf)

**Comment by aitzaz70** [comment]
> Maybe you have too many unread chats or old session id

The problem is solved. I was using WhatsApp Beta Version
