### ISSUE TITLE
Delete 

### ISSUE THREAD

**Issue by Riders004** [Guru322/GURU-BOT#251]
AntiDelete function kese work karta hai sir

**Comment by Guru322** [comment]
checkout    [This](https://github.com/Guru322/GURU-BOT/blob/81dd8e7d035db8646c812db529955a13b485bcb8/handler.js#L725)

And [This too](https://github.com/WhiskeySockets/Baileys#implementing-a-data-store)

**Comment by Guru322** [comment]
[proper Docs](https://whiskeysockets.github.io/Baileys/functions/makeInMemoryStore.html#makeInMemoryStore.__type.loadMessage)

**Comment by Riders004** [comment]
Listener ka code do AntiDelete function ka
