### ISSUE TITLE
BIG FAN 😂

### ISSUE THREAD

**Issue by Riders004** [Guru322/GURU-BOT#271]
Btw wo apka paircode hua kya ek sath 2 log ise kar sake ? Wo bana rhe the na 😶

**Comment by Guru322** [comment]
my pairing code handle 69 users at same time

**Comment by Guru322** [comment]
but latest baileys update se dead hai , aur time nahi mila mujhe fix karne ke

**Comment by Guru322** [comment]
> Btw wo apka paircode hua kya ek sath 2 log ise kar sake ? Wo bana rhe the na 😶

https://github.com/WhiskeySockets/Baileys/issues/597#issuecomment-1901384326

ye check karle , tera paircode fix ho jayega

**Comment by Riders004** [comment]
> > Btw wo apka paircode hua kya ek sath 2 log ise kar sake ? Wo bana rhe the na 😶
> 
> [WhiskeySockets/Baileys#597 (comment)](https://github.com/WhiskeySockets/Baileys/issues/597#issuecomment-1901384326)
> 
> ye check karle , tera paircode fix ho jayega

I hvae fixed

**Comment by Guru322** [comment]
> > > Btw wo apka paircode hua kya ek sath 2 log ise kar sake ? Wo bana rhe the na 😶
> > 
> > 
> > [WhiskeySockets/Baileys#597 (comment)](https://github.com/WhiskeySockets/Baileys/issues/597#issuecomment-1901384326)
> > ye check karle , tera paircode fix ho jayega
> 
> I hvae fixed

mai check kar rha tha incorrect code de rha tha

**Comment by Riders004** [comment]
> > > > Btw wo apka paircode hua kya ek sath 2 log ise kar sake ? Wo bana rhe the na 😶
> > > 
> > > 
> > > [WhiskeySockets/Baileys#597 (comment)](https://github.com/WhiskeySockets/Baileys/issues/597#issuecomment-1901384326)
> > > ye check karle , tera paircode fix ho jayega
> > 
> > 
> > I hvae fixed
> 
> mai check kar rha tha incorrect code de rha tha

Kya ?

**Comment by Guru322** [comment]
> > > > > Btw wo apka paircode hua kya ek sath 2 log ise kar sake ? Wo bana rhe the na 😶
> > > > 
> > > > 
> > > > [WhiskeySockets/Baileys#597 (comment)](https://github.com/WhiskeySockets/Baileys/issues/597#issuecomment-1901384326)
> > > > ye check karle , tera paircode fix ho jayega
> > > 
> > > 
> > > I hvae fixed
> > 
> > 
> > mai check kar rha tha incorrect code de rha tha
> 
> Kya ?

i checked your pairing code web  , it's saying incorrect code

**Comment by Riders004** [comment]
> > > > > > Btw wo apka paircode hua kya ek sath 2 log ise kar sake ? Wo bana rhe the na 😶
> > > > > 
> > > > > 
> > > > > [WhiskeySockets/Baileys#597 (comment)](https://github.com/WhiskeySockets/Baileys/issues/597#issuecomment-1901384326)
> > > > > ye check karle , tera paircode fix ho jayega
> > > > 
> > > > 
> > > > I hvae fixed
> > > 
> > > 
> > > mai check kar rha tha incorrect code de rha tha
> > 
> > 
> > Kya ?
> 
> i checked your pairing code web , it's saying incorrect code

Ho hi nahi sakta 😂

**Comment by Riders004** [comment]
> > > > > > Btw wo apka paircode hua kya ek sath 2 log ise kar sake ? Wo bana rhe the na 😶
> > > > > 
> > > > > 
> > > > > [WhiskeySockets/Baileys#597 (comment)](https://github.com/WhiskeySockets/Baileys/issues/597#issuecomment-1901384326)
> > > > > ye check karle , tera paircode fix ho jayega
> > > > 
> > > > 
> > > > I hvae fixed
> > > 
> > > 
> > > mai check kar rha tha incorrect code de rha tha
> > 
> > 
> > Kya ?
> 
> i checked your pairing code web , it's saying incorrect code

Bese ek sath 2 ko use karna bala bana kya ?
