### ISSUE TITLE
❌Exited with code: null

### ISSUE THREAD

**Issue by ifvbdhojvfnevneinvi** [Guru322/GURU-BOT#304]
this error is appears every time after trying to download "ex: facebook video" or large file size {15 mo / 20 mo}
and the bot stopped and didn't restart again in KOYEB

**Comment by Guru322** [comment]
> this error is appears every time after trying to download "ex: facebook video" or large file size {15 mo / 20 mo} and the bot stopped and didn't restart again in KOYEB

Koyeb gives limited Ram , so when you use more than that , it will crash and exit , so either purchase a paid plan of theirs or use heroku
