### ISSUE TITLE
Youtube download is not working 

### ISSUE THREAD

**Issue by rinsanak** [Guru322/GURU-BOT#332]
Youtube download is not working

**Comment by Guru322** [comment]
Audio or video?

**Comment by geniuskelly46** [comment]
How can i be able to deploy bot on my WhatsApp? Facebook? Telegram?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Guru322** [comment]
> How can i be able to deploy bot on my WhatsApp? Facebook? Telegram?


https://host.guruapi.tech/
visit Here

**Comment by rinsanak** [comment]
Video
